### ISSUE TITLE
[REQUEST]: Add information about installing Elastic Agent on Windows

### ISSUE THREAD

**Issue by smnschneider** [elastic/ingest-docs#264] opened 2023-06-16 15:53 UTC
### Description

In the past there were several situations, where customers tried to install the Elastic Agent as Administrator via the "Windows PowerShell ISE". Unfortunately the installation there is not working at all as it breaks or it stalls when trying to execute the install command even though all other commands before worked as exptected. This is a reproduceable behavior.

It would be great to place a hint/information into the documentation to use the actual "Windows PowerShell" as Administrator.

The best place for this would be the installation docs as the user is forwarded there using Kibana to add an Elastic Agent.
![image](https://github.com/elastic/ingest-docs/assets/95302847/c65a6955-68ab-47c9-82ae-4e71fa6134b5)

The link forwards to: [https://www.elastic.co/guide/en/fleet/8.8/install-fleet-managed-elastic-agent.html](https://www.elastic.co/guide/en/fleet/8.8/install-fleet-managed-elastic-agent.html)

### Resources

I dont know what to list here exactly thats why i add the link to the documentation, where this information is missing, again.
[https://www.elastic.co/guide/en/fleet/8.8/install-fleet-managed-elastic-agent.html](https://www.elastic.co/guide/en/fleet/8.8/install-fleet-managed-elastic-agent.html)

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @smnschneider

**Stakeholders:**

**Comment by cmacknz** [comment] 2023-06-20 12:55
Duplicate of https://github.com/elastic/ingest-docs/issues/267, closing.

**Closed by cmacknz** 2023-06-20 12:55 UTC
Labels: Team:Docs, request
