### ISSUE TITLE
[Fleet]: Link icon is misaligned for elasticsearch and logstash output.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#230] opened 2023-05-29 08:55 UTC
**Description:**
Link icon is little below(misaligned with title text) the elasticsearch and logstash output.
For all others, it is exactly with the title text.

**Link:**
- https://www.elastic.co/guide/en/fleet/8.8/fleet-settings.html#es-output-settings
- https://www.elastic.co/guide/en/fleet/8.8/fleet-settings.html#ls-output-settings

**Screen Recording:**

https://github.com/elastic/ingest-docs/assets/77374876/198cb9f5-c47b-4841-9393-da78ba6ebabb

**Comment by amolnater-qasource** [comment] 2023-05-29 09:07
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2023-05-29 09:09
Secondary review for this ticket is Done

**Comment by amitkanfer** [comment] 2023-06-01 18:58
@karenzone who can help us with this one?

**Comment by amolnater-qasource** [comment] 2023-06-13 06:21
Hi @kilfoyle 

Thank you for the fixes and sharing the update.

We will be validating the docs and this issue on the next release.
For further tracking we are adding the required label to this issue.

Thank you!

**Comment by amolnater-qasource** [comment] 2023-11-08 06:29
Hi @kilfoyle 

We have revalidated the latest docs and found this issue as **still reproducible**.

**Observations:**
- Link icon is misaligned for elasticsearch, kafka and logstash output.

**Links are now updated to:**
- https://www.elastic.co/guide/en/fleet/8.11/es-output-settings.html
- https://www.elastic.co/guide/en/fleet/8.11/ls-output-settings.html
- https://www.elastic.co/guide/en/fleet/8.11/kafka-output-settings.html

**Screen Recording:**


https://github.com/elastic/ingest-docs/assets/77374876/4d9f8955-fea1-477b-af74-9df93953fa69



Hence we are **reopening** this issue.

Thanks

**Comment by kilfoyle** [comment] 2024-04-11 18:40
Hi @amolnater-qasource 

It looks like this misalligned link problem now affects every page in the Elastic docs. I randomly checked a few books and pasted the examples below. I'm not sure what changed.

Since it's a general issue affecting all pages and not just the three pages in the Fleet & Agent Guide I'm afraid it's not something I can fix. Thankfully, we plan to start using a new docs system soon and that will look much better.


**EXAMPLES**

---

**Elasticsearch Guide:**
 [What is Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-intro.html)

---

![Screenshot 2024-04-11 at 2 22 27 PM](https://github.com/elastic/ingest-docs/assets/41695641/fe3ee8dd-f49b-4ab1-b4bc-1ddb590d3268)

---

[Upgrade Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html)

![Screenshot 2024-04-11 at 2 22 45 PM](https://github.com/elastic/ingest-docs/assets/41695641/9ebf8a74-6a74-48a2-8725-5dcd59bfa55f)

---

[Upgrade Elasticsearch - index compatibility](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html)

![Screenshot 2024-04-11 at 2 25 39 PM](https://github.com/elastic/ingest-docs/assets/41695641/bf64cb5f-ee16-4f81-a62e-5af7348956a0)

---

**Kibana Guide:**

[Kibana - Your window into Elastic](https://www.elastic.co/guide/en/kibana/current/introduction.html)

![Screenshot 2024-04-11 at 2 28 39 PM](https://github.com/elastic/ingest-docs/assets/41695641/d6069b45-1fcf-4c27-819f-15b0727e058d)

---

**Security Guide**

[Elastic Security overview](https://www.elastic.co/guide/en/security/current/es-overview.html)

![Screenshot 2024-04-11 at 2 28 39 PM](https://github.com/elastic/ingest-docs/assets/41695641/5f0fcbf8-04c4-4aef-b4de-eef339e706b2)

---

**Logstash Reference**

[Logstash introduction](https://www.elastic.co/guide/en/logstash/current/introduction.html)

![Screenshot 2024-04-11 at 2 33 19 PM](https://github.com/elastic/ingest-docs/assets/41695641/6676ae18-c774-441f-a35b-4da6082cf041)

**Comment by kilfoyle** [comment] 2024-04-12 18:24
I think we can close this as expected behavior, since it (unfortunately) affects the whole docs set.

**Closed by kilfoyle** 2024-04-12 18:24 UTC
Labels: bug, Team:Docs, Team:Fleet

**Comment by amolnater-qasource** [comment] 2024-04-24 04:48
Thank you for confirming as expected behavior @kilfoyle
